name: CI/CD Pipeline

env:
  APP_ENV: dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Quality Checks
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: api_demo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, dom, filter, gd, json, pgsql
        coverage: pcov

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: make install

    - name: Reset database
      env:
        DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/api_demo?serverVersion=16&charset=utf8
      run: make db-reset

    - name: Warm up cache for PHPStan
      env:
        DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/api_demo?serverVersion=16&charset=utf8
      run: php bin/console cache:warmup

    - name: Run PHPStan (Static Analysis)
      env:
        DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/api_demo?serverVersion=16&charset=utf8
      run: make phpstan

    - name: Run PHP CS Fixer (Code Style Check)
      run: make cs-check

    - name: Create test database
      env:
        DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/api_demo?serverVersion=16&charset=utf8
      run: make db-test-setup

    - name: Run PHPUnit Tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/api_demo?serverVersion=16&charset=utf8
      run: make test

    - name: Run Security Check
      run: make security-check

    - name: Check for Schema Drift
      id: schema-check
      env:
        DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/api_demo?serverVersion=16&charset=utf8
      run: |
        OUTPUT=$(php bin/console doctrine:migrations:diff --no-interaction --quiet 2>&1 || true)
        echo "output<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        if [[ -n "$OUTPUT" ]]; then
          echo "has_drift=true" >> $GITHUB_OUTPUT
        else
          echo "has_drift=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Fail if Schema Drift Detected
      if: steps.schema-check.outputs.has_drift == 'true'
      run: |
        echo "::error::Schema drift detected! Your entity definitions don't match the database schema."
        echo "::error::Run 'php bin/console doctrine:migrations:diff' locally to generate a migration."
        echo "${{ steps.schema-check.outputs.output }}"
        exit 1

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Run security audit
      run: composer audit
