name: Code Style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv
        coverage: none

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Check code style (main branch)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        make cs-check
        if [ $? -ne 0 ]; then
          echo "❌ Code style issues found on main branch!"
          echo "Please run 'make cs-fix' locally and commit the changes."
          exit 1
        fi

    - name: Check and fix code style (pull requests)
      if: github.event_name == 'pull_request'
      run: |
        make cs-check
        if [ $? -ne 0 ]; then
          echo "🔧 Code style issues found. Auto-fixing..."
          make cs-fix
          
          if [[ `git status --porcelain` ]]; then
            git config --local user.email "code-style-bot@github.com"
            git config --local user.name "Code Style Bot"
            git add .
            git commit -m "🤖 Auto-fix code style issues" -m "This commit was automatically generated by the Code Style Bot to fix PHP CS Fixer violations found in your pull request." -m "To avoid this in the future, run 'make cs-fix' before pushing."
            git push
            echo "✅ Code style issues have been automatically fixed and committed."
          else
            echo "✅ All code style issues resolved."
          fi
        else
          echo "✅ No code style issues found."
        fi
